[package]
name = "cw"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rayon = "1.10.0"
tokio = { version = "1.44.1", features = ["rt", "macros", "rt-multi-thread"] }
wgpu = "24.0.1"
winit = "0.30.9"
